<?php

/**
 * Translate string
 */
//homepage
pll_register_string("Homepage", "Homepage");
pll_register_string("Need Help? Contact Us!", "Need Help? Contact Us!");
pll_register_string("Email:", "Email:");
pll_register_string("close", "close");
pll_register_string("Paint my Desire", "Paint my Desire");
pll_register_string("All rights reserved", "All rights reserved");
pll_register_string("Localization Settings", "Localization Settings");
pll_register_string("We can", "We can");
pll_register_string("paint", "paint");
pll_register_string("your Desire", "your Desire");
pll_register_string("Order Now", "Order Now");
pll_register_string("Scroll down to see more", "Scroll down to see more");
pll_register_string("Your browser does not support the video tag.", "Your browser does not support the video tag.");
pll_register_string("See More", "See More");
pll_register_string("or", "or");
pll_register_string("Classic", "Classic");
pll_register_string("Emphasize All Colours", "Emphasize All Colours");
pll_register_string("High Effort", "High Effort");
pll_register_string("Read More", "Read More");
pll_register_string("English", "English");
pll_register_string("German", "German");
pll_register_string("Gallery", "Gallery");
pll_register_string("Choose Your Favourite Portrait Inspiration", "Choose Your Favourite Portrait Inspiration");
pll_register_string("Style", "Style");
pll_register_string("Subject", "Subject");
pll_register_string("your inspiration", "your inspiration");
pll_register_string("prev", "prev");
pll_register_string("next", "next");
pll_register_string("Prev", "Prev");
pll_register_string("Next", "Next");
pll_register_string("Oopps... Something went wrong", "Oopps... Something went wrong", "Oopps... Something went wrong", "Oopps... Something went wrong");
pll_register_string("We are already working to fix this error. You can return to the main page to continue working with the site.", "We are already working to fix this error. You can return to the main page to continue working with the site.");
pll_register_string("Go to the Main Page", "Go to the Main Page");
pll_register_string("I Want It", "I Want It");
pll_register_string("Home", "Home");
pll_register_string("Page %d", "Page %d");
pll_register_string("Search results for query - <b>%s</b>", "Search results for query - <b>%s</b>");
pll_register_string("Author's archive: <b>%s</b>", "Author's archive: <b>%s</b>");
pll_register_string("Archive for <b>%d</b> year", "Archive for <b>%d</b> year");
pll_register_string("Archive for: <b>%s</b>", "Archive for: <b>%s</b>");
pll_register_string("Media: %s", "Media: %s");
pll_register_string("Records by tag: <b>%s</b>", "Records by tag: <b>%s</b>");
pll_register_string('%1$s from %2$s by tag: <b>%3$s</b>', '%1$s from %2$s by tag: <b>%3$s</b>');
pll_register_string("Home", "Home");
pll_register_string("Blog", "Blog");
pll_register_string("step", "step");
pll_register_string("Share an article with:", "Share an article with:");
pll_register_string("Jan", "Jan");
pll_register_string("Feb", "Feb");
pll_register_string("Mar", "Mar");
pll_register_string("Apr", "Apr");
pll_register_string("May", "May");
pll_register_string("Jun", "Jun");
pll_register_string("Jul", "Jul");
pll_register_string("Aug", "Aug");
pll_register_string("Sep", "Sep");
pll_register_string("Oct", "Oct");
pll_register_string("Nov", "Nov");
pll_register_string("Dec", "Dec");
pll_register_string("No records found.", "No records found.");
pll_register_string("All article", "All article");
pll_register_string("Contact Us", "Contact Us");
pll_register_string("Leave your phone number or email and we will contact you", "Leave your phone number or email and we will contact you");
pll_register_string("Email address", "Email address");
pll_register_string("Message (optional)", "Message (optional)");
pll_register_string("Send", "Send");
pll_register_string("Something went wrong...", "Something went wrong...");
pll_register_string("Apparently the payment was unsuccessful. <br>Take a step back and try again.", "Apparently the payment was unsuccessful. <br>Take a step back and try again.");
pll_register_string("Congrats!", "Congrats!");
pll_register_string("Your order has been placed successfully!", "Your order has been placed successfully!");
pll_register_string("View details in your email <a href='mailto:EMAIL'>EMAIL</a>", "View details in your email <a href='mailto:EMAIL'>EMAIL</a>");
pll_register_string("Back", "Back");
pll_register_string("Money Refund", "Money Refund");
pll_register_string("Please fill out this form to get a refund", "Please fill out this form to get a refund");
pll_register_string("Fill in the required fields of the form.", "Fill in the required fields of the form.");
pll_register_string("An error has occurred, please try again or contact us.", "An error has occurred, please try again or contact us.");
pll_register_string("Your request has been sent successfully.", "Your request has been sent successfully.");
pll_register_string("First Name", "First Name");
pll_register_string("Last Name", "Last Name");
pll_register_string("Address line 1", "Address line 1");
pll_register_string("Address line 2 (optional)", "Address line 2 (optional)");
pll_register_string("City", "City");
pll_register_string("State", "State");
pll_register_string("Postal code", "Postal code");
pll_register_string("Country", "Country");
pll_register_string("Choose a reason for refund", "Choose a reason for refund");
$refundReasons = getRefundReasons();
foreach($refundReasons as $code => $refundReason) {
    pll_register_string($refundReason, $refundReason);
}
pll_register_string("Other reason", "Other reason");
pll_register_string("Back", "Back");
pll_register_string("Amount", "Amount");
pll_register_string("Currency", "Currency");
pll_register_string("Sender Name", "Sender Name");
pll_register_string("Recipient Name", "Recipient Name");
pll_register_string("Message", "Message");
pll_register_string("An error occurred. Product not found.", "An error occurred. Product not found.");
pll_register_string("An error occurred. The product cannot be added to the cart.", "An error occurred. The product cannot be added to the cart.");
pll_register_string("An error occurred. Product cannot be deleted.", "An error occurred. Product cannot be deleted.");
pll_register_string("days", "days");
pll_register_string("Charcoal", "Charcoal");
pll_register_string("Medium oil portraits", "Medium oil portraits");
pll_register_string("Large oil portraits", "Large oil portraits");
pll_register_string("all sizes", "all sizes");
pll_register_string("Normal", "Normal");
pll_register_string("Express Service", "Express Service");
pll_register_string("Super Express Service", "Super Express Service");
pll_register_string("Request", "Request");
pll_register_string("Pricing", "Pricing");
pll_register_string("Custom size", "Custom size");
pll_register_string("Click Here", "Click Here");
pll_register_string("size", "size");
pll_register_string("price", "price");
pll_register_string("Our prices starts at", "Our prices starts at");
pll_register_string("Duration", "Duration");
pll_register_string("delivery type", "delivery type");
pll_register_string("duration", "duration");

//order page start
pll_register_string("Order Your Portrait in 3 Steps", "Order Your Portrait in 3 Steps");
pll_register_string("Portrait Characteristic", "Portrait Characteristic");
pll_register_string("Upload Portrait", "Upload Portrait");
pll_register_string("Checkout", "Checkout");
pll_register_string("Choose number of subjects", "Choose number of subjects");
pll_register_string("1 person", "1 person");
pll_register_string("2 person", "2 person");
pll_register_string("1 pet", "1 pet");
pll_register_string("1 person + 1 pet", "1 person + 1 pet");
pll_register_string("Landscape", "Landscape");
pll_register_string("Custom", "Custom");
pll_register_string("Persons", "Persons");
pll_register_string("Pets", "Pets");
pll_register_string("Choose your Painting Technique", "Choose your Painting Technique");
pll_register_string("Choose your size", "Choose your size");
pll_register_string("Background", "Background");
pll_register_string("Choose a background", "Choose a background");
pll_register_string("Choose a background color", "Choose a background color");
pll_register_string("Artist to choose background (popular)", "Artist to choose background (popular)");
pll_register_string("Photo background", "Photo background");
pll_register_string("Background colour (pick yours next)", "Background colour (pick yours next)");
pll_register_string("Beige", "Beige");
pll_register_string("Black", "Black");
pll_register_string("Blue Bronze", "Blue Bronze");
pll_register_string("Cold Blue", "Cold Blue");
pll_register_string("Warm Green", "Warm Green");
pll_register_string("White", "White");
pll_register_string("Continue", "Continue");
pll_register_string("Add to Cart", "Add to Cart");
pll_register_string("Upload one or more photos", "Upload one or more photos");
pll_register_string("Add the Photo(s) You would like Painted", "Add the Photo(s) You would like Painted");
pll_register_string("Drag the Photo here", "Drag the Photo here");
pll_register_string("Upload Photo", "Upload Photo");
pll_register_string("Get the artistis advice on which Photos will be Best for my Painting", "Get the artistis advice on which Photos will be Best for my Painting");
pll_register_string("Second option to send us the Photo", "Second option to send us the Photo");
pll_register_string("Mail your hardcopy photo(s) to:", "Mail your hardcopy photo(s) to:");
pll_register_string("Comments e.g. Which Person where? Which Position?", "Comments e.g. Which Person where? Which Position?");
pll_register_string("Frames", "Frames");
pll_register_string("Yes, I need a frame for My Portrait", "Yes, I need a frame for My Portrait");
pll_register_string("I buy myself a picture frame", "I buy myself a picture frame");
pll_register_string("Your Portrait", "Your Portrait");
pll_register_string("Style", "Style");
pll_register_string("Person / Pets", "Person / Pets");
pll_register_string("Size", "Size");
pll_register_string("Background", "Background");
pll_register_string("Edit your order", "Edit your order");
pll_register_string("Add an additional Painting to your order and get 30 $ Discount!", "Add an additional Painting to your order and get 30 $ Discount!");
pll_register_string("+ Add an extra photo", "+ Add an extra photo");
pll_register_string("Delivery at your Door", "Delivery at your Door");
pll_register_string("Get it on:", "Get it on:");
pll_register_string("For Free", "For Free");
pll_register_string("15% Extra", "15% Extra");
pll_register_string("30% Extra", "30% Extra");
pll_register_string("50% Extra", "50% Extra");
pll_register_string("Characteristics", "Characteristics");
pll_register_string("Material & Framing", "Material & Framing");
pll_register_string("Read More", "Read More");
pll_register_string("subject max", "subject max");
pll_register_string("popular", "popular");
pll_register_string("Monday", "Monday");
pll_register_string("Tuesday", "Tuesday");
pll_register_string("Wednesday", "Wednesday");
pll_register_string("Thursday", "Thursday");
pll_register_string("Friday", "Friday");
pll_register_string("Saturday", "Saturday");
pll_register_string("Sunday", "Sunday");
pll_register_string("Error", "Error");
pll_register_string("An error occurred while uploading image.", "An error occurred while uploading image.");
pll_register_string("Number of subject is empty.", "Number of subject is empty.");
pll_register_string("You choose too many number of subjects. Please change number of subjects.", "You choose too many number of subjects. Please change number of subjects.");
pll_register_string("Painting Technique is empty.", "Painting Technique is empty.");
pll_register_string("Size is empty.", "Size is empty.");
pll_register_string("Background is empty.", "Background is empty.");
pll_register_string("Delivery Type is empty.", "Delivery Type is empty.");
pll_register_string("Delivery Date is empty.", "Delivery Date is empty.");
pll_register_string("An error occurred while uploading image.", "An error occurred while uploading image.");
pll_register_string("Photos are missing.", "Photos are missing.");
pll_register_string("Style", "Style");
pll_register_string("Person / Pets", "Person / Pets");
pll_register_string("Size", "Size");
pll_register_string("Background", "Background");
pll_register_string("Edit your order", "Edit your order");
pll_register_string("Add an additional Painting to your order and get", "Add an additional Painting to your order and get");
pll_register_string("Discount", "Discount");
pll_register_string("Add an extra photo", "Add an extra photo");
pll_register_string("Order Editing", "Order Editing");
pll_register_string("Order Editing Text", "Order Editing Text");
pll_register_string("Save", "Save");
pll_register_string("Cart", "Cart");
pll_register_string("Total Amount", "Total Amount");
pll_register_string("Gift Card", "Gift Card");
pll_register_string("Only 16 persons are possible for oil.", "Only 16 persons are possible for oil.");
pll_register_string("Only 7 persons are possible for charcoal.", "Only 7 persons are possible for charcoal.");
pll_register_string("Old price", "Old price");
pll_register_string("Product cannot be deleted. This Product has discount related products.", "Product cannot be deleted. This Product has discount related products.");
pll_register_string("Amount Details", "Amount Details");
pll_register_string("Amount Details", "Amount Details");
pll_register_string("I have a gift card", "I have a gift card");
pll_register_string("Insert here", "Insert here");
pll_register_string("Apply", "Apply");
pll_register_string("was applied", "was applied");
pll_register_string("Cancel", "Cancel");
pll_register_string("Amount Details Text", "Amount Details Text");
pll_register_string("Sub Total", "Sub Total");
pll_register_string("Shipping Country", "Shipping Country");
pll_register_string("Free", "Free");
pll_register_string("Gift Card Discount", "Gift Card Discount");
pll_register_string("Gift Card is empty.", "Gift Card is empty.");
pll_register_string('Coupon "___" does not exist!', 'Coupon "___" does not exist!');
pll_register_string("Shipping Address", "Shipping Address");
pll_register_string("Shipping Address Text", "Shipping Address Text");
pll_register_string("Message (optional)", "Message (optional)");
pll_register_string("First Name is missing.", "First Name is missing.");
pll_register_string("Last Name is missing.", "Last Name is missing.");
pll_register_string("Address is missing.", "Address is missing.");
pll_register_string("City is missing.", "City is missing.");
pll_register_string("State is missing.", "State is missing.");
pll_register_string("Postal Code is missing.", "Postal Code is missing.");
pll_register_string("Country is missing.", "Country is missing.");
pll_register_string("Phone is missing.", "Phone is missing.");
pll_register_string("Email is missing.", "Email is missing.");
pll_register_string("Payment Method", "Payment Method");
pll_register_string("All transaction are secure and encripted. Credit card information is never stored.", "All transaction are secure and encripted. Credit card information is never stored.");
pll_register_string("Cart Details", "Cart Details");
pll_register_string("Back", "Back");
pll_register_string("Back", "Back");
pll_register_string("Back", "Back");

$countries = getCountries();
foreach($countries as $code => $country) {
    pll_register_string($country, $country);
}
// <?php pll_e("Homepage"); ?>
